export const GAME_NAME = "Aljama";
export const GAME_SUB = "Caminantes del Velo";

export const RARITIES = {
  comun: { name: "Común", color: "#8a7a62", mult: 1, value: 1 },
  notable: { name: "Notable", color: "#1a9b8e", mult: 1.25, value: 1.6 },
  raro: { name: "Raro", color: "#c45c26", mult: 1.55, value: 2.4 },
  relicario: { name: "Relicario", color: "#d4a84b", mult: 2, value: 4 },
};

export const CLASSES = {
  warrior: {
    id: "warrior",
    name: "Guerrero",
    role: "Vanguardia",
    blurb: "Muro de adobe y bronce. Sostiene la primera línea y obliga al enemigo a mirarlo.",
    colors: ["#c45c26", "#f0c27a", "#8b3a2a"],
    stats: { str: 8, mag: 2, vit: 8, agi: 4, spi: 3 },
    hp: 46,
    skills: ["slash", "guard", "charge", "taunt"],
    prefer: [1, 2],
  },
  mage: {
    id: "mage",
    name: "Mago",
    role: "Canal",
    blurb: "Dobla el calor residual del eclipse. Frágil, pero capaz de romper formaciones enteras.",
    colors: ["#5b4db0", "#9fd4ff", "#2a2158"],
    stats: { str: 2, mag: 9, vit: 3, agi: 5, spi: 6 },
    hp: 28,
    skills: ["ember", "meteor", "frost", "ward"],
    prefer: [3, 4],
  },
  cleric: {
    id: "cleric",
    name: "Clérigo",
    role: "Baliza",
    blurb: "Custodia el último faro interior. Cura, bendice y golpea con luz densa.",
    colors: ["#e8a317", "#fff3c4", "#8a5a12"],
    stats: { str: 4, mag: 6, vit: 6, agi: 3, spi: 8 },
    hp: 36,
    skills: ["smite", "heal", "bless", "sanctuary"],
    prefer: [2, 3],
  },
  rogue: {
    id: "rogue",
    name: "Pícaro",
    role: "Filo",
    blurb: "Camina el borde de las dunas. Corta tendones, envenena y desvalija lo que aún late.",
    colors: ["#2f6b5a", "#b7e4c7", "#16352c"],
    stats: { str: 6, mag: 3, vit: 4, agi: 9, spi: 3 },
    hp: 32,
    skills: ["stab", "veil", "venom", "pilfer"],
    prefer: [1, 2],
  },
  ranger: {
    id: "ranger",
    name: "Explorador",
    role: "Ojo",
    blurb: "Lee el canto del cristal-arena. Dispara desde atrás y marca a quien debe caer primero.",
    colors: ["#3d7a3a", "#d4e09b", "#21401f"],
    stats: { str: 6, mag: 3, vit: 5, agi: 8, spi: 4 },
    hp: 34,
    skills: ["arrow", "volley", "snare", "mark"],
    prefer: [3, 4],
  },
  bard: {
    id: "bard",
    name: "Bardo",
    role: "Eco",
    blurb: "Afina el viento entre las tejas. Cambia el ritmo de toda la compañía con una sola frase.",
    colors: ["#b03d6a", "#ffc2d4", "#5a1d38"],
    stats: { str: 3, mag: 6, vit: 4, agi: 6, spi: 8 },
    hp: 30,
    skills: ["chord", "hymn", "crescendo", "dissonance"],
    prefer: [3, 4],
  },
  alchemist: {
    id: "alchemist",
    name: "Alquimista",
    role: "Crisol",
    blurb: "Destila el jugo del invernadero. Quema filas enteras con dosis cortas y remienda con tónicos.",
    colors: ["#6a8f2a", "#e4f0a8", "#3a4a12"],
    stats: { str: 3, mag: 8, vit: 5, agi: 5, spi: 6 },
    hp: 33,
    skills: ["vial", "tonic", "fumes", "flask"],
    prefer: [2, 3],
  },
  weaver: {
    id: "weaver",
    name: "Tejedor",
    role: "Hilo",
    blurb: "Tira de los hilos del velo. Arrastra enemigos al frente, ata pies y deshace refuerzos.",
    colors: ["#2a6b7a", "#9fe4e0", "#123840"],
    stats: { str: 3, mag: 7, vit: 4, agi: 6, spi: 7 },
    hp: 31,
    skills: ["tug", "bind", "stitch", "unweave"],
    prefer: [3, 4],
  },
  dancer: {
    id: "dancer",
    name: "Danzante",
    role: "Paso",
    blurb: "Cambia de puesto en un giro. Golpea desde cualquier fila y empuja a un aliado al sitio que deja.",
    colors: ["#c45a7a", "#ffd4c2", "#6a2040"],
    stats: { str: 5, mag: 3, vit: 4, agi: 10, spi: 4 },
    hp: 30,
    skills: ["lash", "step", "flourish", "encore"],
    prefer: [2, 3],
  },
};

export const BASIC_SKILL = {
  id: "nudge",
  name: "Empuje",
  desc: "Golpe improvisado. Desde cualquier puesto, solo contra la primera línea.",
  launch: [1, 2, 3, 4],
  target: { type: "enemy", ranks: [1, 2] },
  power: 6,
  scaling: "str",
  kind: "phys",
  crit: 0.05,
  fx: "nudge",
};

export const SKILLS = {
  slash: {
    id: "slash",
    name: "Tajo de adobe",
    desc: "Corte pesado contra la primera línea.",
    launch: [1, 2],
    target: { type: "enemy", ranks: [1, 2] },
    power: 11,
    scaling: "str",
    kind: "phys",
    crit: 0.08,
    fx: "slash",
  },
  guard: {
    id: "guard",
    name: "Muro solar",
    desc: "Alza el escudo. Gana defensa durante 2 turnos.",
    launch: [1, 2],
    target: { type: "self" },
    power: 0,
    kind: "buff",
    fx: "guard",
    effects: [{ type: "def", amount: 6, turns: 2 }],
  },
  charge: {
    id: "charge",
    name: "Carga de duna",
    desc: "Arremete en profundidad. Alto daño, un solo objetivo.",
    launch: [1],
    target: { type: "enemy", ranks: [1, 2, 3] },
    power: 16,
    scaling: "str",
    kind: "phys",
    crit: 0.12,
    fx: "charge",
  },
  taunt: {
    id: "taunt",
    name: "Provocar",
    desc: "Te marca como amenaza. Los enemigos que puedan alcanzarte deben golpearte.",
    launch: [1, 2],
    target: { type: "enemy", ranks: [1, 2, 3] },
    power: 4,
    scaling: "str",
    kind: "phys",
    fx: "taunt",
    effects: [
      { type: "taunt", amount: 1, turns: 3, on: "self" },
      { type: "atk", amount: -3, turns: 2 },
    ],
  },
  ember: {
    id: "ember",
    name: "Brasa del velo",
    desc: "Llama precisa a cualquier rango.",
    launch: [3, 4],
    target: { type: "enemy", ranks: [1, 2, 3, 4] },
    power: 12,
    scaling: "mag",
    kind: "magic",
    crit: 0.1,
    fx: "fire",
  },
  meteor: {
    id: "meteor",
    name: "Granizo de sol",
    desc: "Lluvia ardiente sobre todos los enemigos.",
    launch: [4],
    target: { type: "allEnemies" },
    power: 8,
    scaling: "mag",
    kind: "magic",
    crit: 0.05,
    fx: "meteor",
  },
  frost: {
    id: "frost",
    name: "Escarcha de sal",
    desc: "Congela el ritmo del objetivo. Pierde agilidad.",
    launch: [3, 4],
    target: { type: "enemy", ranks: [1, 2, 3, 4] },
    power: 7,
    scaling: "mag",
    kind: "magic",
    fx: "frost",
    effects: [{ type: "agi", amount: -4, turns: 2 }],
  },
  ward: {
    id: "ward",
    name: "Barrera de vidrio",
    desc: "Envuelve a un aliado con un escudo de luz.",
    launch: [3, 4],
    target: { type: "ally", ranks: [1, 2, 3, 4] },
    power: 0,
    kind: "buff",
    fx: "ward",
    effects: [{ type: "shield", amount: 12, turns: 2 }],
  },
  smite: {
    id: "smite",
    name: "Martillo de faro",
    desc: "Golpe consagrado contra el frente.",
    launch: [2, 3],
    target: { type: "enemy", ranks: [1, 2] },
    power: 10,
    scaling: "spi",
    kind: "magic",
    crit: 0.08,
    fx: "smite",
  },
  heal: {
    id: "heal",
    name: "Sutura de ámbar",
    desc: "Cierra heridas de un compañero.",
    launch: [2, 3, 4],
    target: { type: "ally", ranks: [1, 2, 3, 4] },
    power: 16,
    scaling: "spi",
    kind: "heal",
    fx: "heal",
  },
  bless: {
    id: "bless",
    name: "Bendición de aljama",
    desc: "Toda la compañía golpea con más fuerza.",
    launch: [3, 4],
    target: { type: "allAllies" },
    power: 0,
    kind: "buff",
    fx: "bless",
    effects: [{ type: "atk", amount: 4, turns: 3 }],
  },
  sanctuary: {
    id: "sanctuary",
    name: "Resguardo",
    desc: "Limpia un mal y cura un poco.",
    launch: [2, 3, 4],
    target: { type: "ally", ranks: [1, 2, 3, 4] },
    power: 8,
    scaling: "spi",
    kind: "heal",
    fx: "cleanse",
    effects: [{ type: "cleanse", amount: 1, turns: 0 }],
  },
  stab: {
    id: "stab",
    name: "Puñalada",
    desc: "Filo corto. Alta probabilidad de crítico.",
    launch: [1, 2],
    target: { type: "enemy", ranks: [1, 2] },
    power: 10,
    scaling: "str",
    kind: "phys",
    crit: 0.28,
    fx: "stab",
  },
  veil: {
    id: "veil",
    name: "Velo de sombra",
    desc: "Te desdibuja. Ganas evasión.",
    launch: [1, 2, 3],
    target: { type: "self" },
    power: 0,
    kind: "buff",
    fx: "veil",
    effects: [{ type: "dodge", amount: 35, turns: 2 }],
  },
  venom: {
    id: "venom",
    name: "Hiel de escorpión",
    desc: "Envenena. El objetivo sangra sal durante 3 turnos.",
    launch: [2, 3],
    target: { type: "enemy", ranks: [1, 2, 3] },
    power: 6,
    scaling: "agi",
    kind: "phys",
    fx: "poison",
    effects: [{ type: "dot", amount: 5, turns: 3 }],
  },
  pilfer: {
    id: "pilfer",
    name: "Desvalijar",
    desc: "Hiere y extrae solis extra del enemigo.",
    launch: [2, 3],
    target: { type: "enemy", ranks: [1, 2] },
    power: 8,
    scaling: "agi",
    kind: "phys",
    fx: "gold",
    effects: [{ type: "gold", amount: 8, turns: 0 }],
  },
  arrow: {
    id: "arrow",
    name: "Flecha de cristal",
    desc: "Disparo limpio a cualquier rango.",
    launch: [3, 4],
    target: { type: "enemy", ranks: [1, 2, 3, 4] },
    power: 11,
    scaling: "agi",
    kind: "phys",
    crit: 0.14,
    fx: "arrow",
  },
  volley: {
    id: "volley",
    name: "Salva",
    desc: "Dos flechas contra objetivos distintos.",
    launch: [4],
    target: { type: "allEnemies" },
    power: 7,
    scaling: "agi",
    kind: "phys",
    crit: 0.08,
    maxHits: 2,
    fx: "volley",
  },
  snare: {
    id: "snare",
    name: "Trampa de juncos",
    desc: "Inmoviliza el frente enemigo y reduce su agilidad.",
    launch: [3, 4],
    target: { type: "enemy", ranks: [1, 2] },
    power: 5,
    scaling: "agi",
    kind: "phys",
    fx: "snare",
    effects: [{ type: "agi", amount: -5, turns: 2 }],
  },
  mark: {
    id: "mark",
    name: "Marca del ojo",
    desc: "El marcado recibe más daño.",
    launch: [3, 4],
    target: { type: "enemy", ranks: [1, 2, 3, 4] },
    power: 4,
    scaling: "agi",
    kind: "phys",
    fx: "mark",
    effects: [{ type: "marked", amount: 6, turns: 3 }],
  },
  chord: {
    id: "chord",
    name: "Cuerda cortante",
    desc: "Nota afilada contra las filas traseras.",
    launch: [3, 4],
    target: { type: "enemy", ranks: [2, 3, 4] },
    power: 10,
    scaling: "mag",
    kind: "magic",
    crit: 0.1,
    fx: "chord",
  },
  hymn: {
    id: "hymn",
    name: "Himno de tejas",
    desc: "Cura ligera a toda la compañía.",
    launch: [3, 4],
    target: { type: "allAllies" },
    power: 8,
    scaling: "spi",
    kind: "heal",
    fx: "hymn",
  },
  crescendo: {
    id: "crescendo",
    name: "Crescendo",
    desc: "El ritmo sube. Más daño para todos.",
    launch: [3, 4],
    target: { type: "allAllies" },
    power: 0,
    kind: "buff",
    fx: "crescendo",
    effects: [{ type: "atk", amount: 5, turns: 2 }],
  },
  dissonance: {
    id: "dissonance",
    name: "Disonancia",
    desc: "Rompe la cadencia enemiga. Menos ataque para todos ellos.",
    launch: [3, 4],
    target: { type: "allEnemies" },
    power: 3,
    scaling: "mag",
    kind: "magic",
    fx: "dissonance",
    effects: [{ type: "atk", amount: -4, turns: 2 }],
  },
  vial: {
    id: "vial",
    name: "Vial de verdín",
    desc: "Ácido corto contra las filas medias y traseras.",
    launch: [2, 3],
    target: { type: "enemy", ranks: [2, 3, 4] },
    power: 9,
    scaling: "mag",
    kind: "magic",
    crit: 0.08,
    fx: "poison",
    effects: [{ type: "dot", amount: 4, turns: 2 }],
  },
  tonic: {
    id: "tonic",
    name: "Tónico de musgo",
    desc: "Cura a un aliado y le da un empujón de ataque.",
    launch: [2, 3, 4],
    target: { type: "ally", ranks: [1, 2, 3, 4] },
    power: 12,
    scaling: "spi",
    kind: "heal",
    fx: "heal",
    effects: [{ type: "atk", amount: 3, turns: 2 }],
  },
  fumes: {
    id: "fumes",
    name: "Vapores del crisol",
    desc: "Nube densa. Daño menor a todos y menos ataque.",
    launch: [3, 4],
    target: { type: "allEnemies" },
    power: 4,
    scaling: "mag",
    kind: "magic",
    fx: "sand",
    effects: [{ type: "atk", amount: -3, turns: 2 }],
  },
  flask: {
    id: "flask",
    name: "Frasco cegador",
    desc: "Estalla en el frente. Baja la agilidad.",
    launch: [2, 3],
    target: { type: "enemy", ranks: [1, 2] },
    power: 8,
    scaling: "mag",
    kind: "magic",
    fx: "frost",
    effects: [{ type: "agi", amount: -4, turns: 2 }],
  },
  tug: {
    id: "tug",
    name: "Jalón de hilo",
    desc: "Arrastra a un enemigo de atrás hacia el frente.",
    launch: [3, 4],
    target: { type: "enemy", ranks: [2, 3, 4] },
    power: 6,
    scaling: "mag",
    kind: "magic",
    fx: "snare",
    effects: [{ type: "pull", amount: 1, turns: 0 }],
  },
  bind: {
    id: "bind",
    name: "Atadura viva",
    desc: "Enreda pies. Pierde mucha agilidad.",
    launch: [3, 4],
    target: { type: "enemy", ranks: [1, 2, 3] },
    power: 5,
    scaling: "mag",
    kind: "magic",
    fx: "snare",
    effects: [{ type: "agi", amount: -6, turns: 2 }],
  },
  stitch: {
    id: "stitch",
    name: "Puntada de velo",
    desc: "Cose un escudo de luz sobre un aliado.",
    launch: [3, 4],
    target: { type: "ally", ranks: [1, 2, 3, 4] },
    power: 0,
    kind: "buff",
    fx: "ward",
    effects: [{ type: "shield", amount: 14, turns: 2 }],
  },
  unweave: {
    id: "unweave",
    name: "Deshacer",
    desc: "Rompe los refuerzos de todos los enemigos.",
    launch: [4],
    target: { type: "allEnemies" },
    power: 2,
    scaling: "mag",
    kind: "magic",
    fx: "curse",
    effects: [{ type: "strip", amount: 1, turns: 0 }],
  },
  lash: {
    id: "lash",
    name: "Látigo de pétalo",
    desc: "Corte ágil. Se lanza desde casi cualquier puesto.",
    launch: [1, 2, 3],
    target: { type: "enemy", ranks: [1, 2, 3] },
    power: 9,
    scaling: "agi",
    kind: "phys",
    crit: 0.16,
    fx: "slash",
  },
  step: {
    id: "step",
    name: "Paso cambiado",
    desc: "Cambia de puesto con un aliado y ganas evasión.",
    launch: [1, 2, 3, 4],
    target: { type: "ally", ranks: [1, 2, 3, 4] },
    power: 0,
    kind: "buff",
    fx: "veil",
    effects: [
      { type: "swap", amount: 1, turns: 0 },
      { type: "dodge", amount: 25, turns: 2 },
    ],
  },
  flourish: {
    id: "flourish",
    name: "Mudanza",
    desc: "Toda la compañía gana evasión un instante.",
    launch: [2, 3, 4],
    target: { type: "allAllies" },
    power: 0,
    kind: "buff",
    fx: "veil",
    effects: [{ type: "dodge", amount: 20, turns: 1 }],
  },
  encore: {
    id: "encore",
    name: "Cierre de danza",
    desc: "Golpe final desde cualquier puesto. Alto crítico.",
    launch: [1, 2, 3, 4],
    target: { type: "enemy", ranks: [1, 2] },
    power: 11,
    scaling: "agi",
    kind: "phys",
    crit: 0.3,
    fx: "stab",
  },
};

export const ENEMY_SKILLS = {
  saltcut: {
    id: "saltcut",
    name: "Cuchilla de sal",
    launch: [1, 2, 3, 4],
    target: { type: "enemy", ranks: [1, 2] },
    power: 6,
    scaling: "str",
    kind: "phys",
    fx: "slash",
  },
  blinddust: {
    id: "blinddust",
    name: "Puñado cegador",
    launch: [1, 2],
    target: { type: "enemy", ranks: [1, 2, 3] },
    power: 3,
    scaling: "agi",
    kind: "phys",
    fx: "sand",
    effects: [{ type: "atk", amount: -3, turns: 2 }],
  },
  sting: {
    id: "sting",
    name: "Aguijón de vidrio",
    launch: [1, 2, 3],
    target: { type: "enemy", ranks: [1, 2] },
    power: 5,
    scaling: "agi",
    kind: "phys",
    fx: "poison",
    effects: [{ type: "dot", amount: 2, turns: 2 }],
  },
  glassspit: {
    id: "glassspit",
    name: "Saliva de vidrio",
    launch: [2, 3, 4],
    target: { type: "enemy", ranks: [1, 2, 3, 4] },
    power: 5,
    scaling: "mag",
    kind: "magic",
    fx: "frost",
    effects: [{ type: "agi", amount: -3, turns: 2 }],
  },
  carapace: {
    id: "carapace",
    name: "Caparazón",
    launch: [1, 2, 3, 4],
    target: { type: "self" },
    power: 0,
    kind: "buff",
    fx: "guard",
    effects: [{ type: "def", amount: 5, turns: 2 }],
  },
  voidtouch: {
    id: "voidtouch",
    name: "Toque vacío",
    launch: [1, 2, 3, 4],
    target: { type: "enemy", ranks: [1, 2, 3, 4] },
    power: 6,
    scaling: "mag",
    kind: "magic",
    fx: "curse",
  },
  curse: {
    id: "curse",
    name: "Maldición seca",
    launch: [2, 3, 4],
    target: { type: "enemy", ranks: [1, 2, 3, 4] },
    power: 3,
    scaling: "mag",
    kind: "magic",
    fx: "curse",
    effects: [{ type: "atk", amount: -3, turns: 2 }],
  },
  disperse: {
    id: "disperse",
    name: "Dispersarse",
    launch: [1, 2, 3, 4],
    target: { type: "self" },
    power: 0,
    kind: "buff",
    fx: "veil",
    effects: [{ type: "dodge", amount: 30, turns: 2 }],
  },
  slam: {
    id: "slam",
    name: "Embestida de adobe",
    launch: [1, 2],
    target: { type: "enemy", ranks: [1, 2] },
    power: 7,
    scaling: "str",
    kind: "phys",
    fx: "charge",
    effects: [{ type: "shove", amount: 1, turns: 0 }],
  },
  adobedust: {
    id: "adobedust",
    name: "Polvo de adobe",
    launch: [1, 2],
    target: { type: "allEnemies" },
    power: 1,
    scaling: "str",
    kind: "phys",
    fx: "sand",
    aoeScale: 0.22,
    effects: [{ type: "atk", amount: -2, turns: 2 }],
  },
  harden: {
    id: "harden",
    name: "Endurecer",
    launch: [1, 2, 3, 4],
    target: { type: "self" },
    power: 0,
    kind: "buff",
    fx: "guard",
    effects: [{ type: "def", amount: 6, turns: 2 }],
  },
  coralbite: {
    id: "coralbite",
    name: "Mordida coral",
    launch: [1, 2, 3],
    target: { type: "enemy", ranks: [1, 2] },
    power: 6,
    scaling: "str",
    kind: "phys",
    fx: "poison",
    effects: [{ type: "dot", amount: 2, turns: 2 }],
  },
  tangle: {
    id: "tangle",
    name: "Enredo",
    launch: [1, 2, 3, 4],
    target: { type: "enemy", ranks: [1, 2] },
    power: 4,
    scaling: "agi",
    kind: "phys",
    fx: "snare",
    effects: [{ type: "agi", amount: -4, turns: 2 }],
  },
  swarm: {
    id: "swarm",
    name: "Enjambre de espinas",
    launch: [1, 2, 3, 4],
    target: { type: "allEnemies" },
    power: 3,
    scaling: "agi",
    kind: "phys",
    fx: "volley",
  },
  eclipsray: {
    id: "eclipsray",
    name: "Rayo de eclipse",
    launch: [2, 3, 4],
    target: { type: "enemy", ranks: [1, 2, 3, 4] },
    power: 7,
    scaling: "mag",
    kind: "magic",
    fx: "smite",
  },
  veilhowl: {
    id: "veilhowl",
    name: "Grito del velo",
    launch: [3, 4],
    target: { type: "allEnemies" },
    power: 3,
    scaling: "mag",
    kind: "magic",
    fx: "dissonance",
    effects: [{ type: "atk", amount: -3, turns: 2 }],
  },
  mend: {
    id: "mend",
    name: "Sutura oscura",
    launch: [2, 3, 4],
    target: { type: "ally", ranks: [1, 2, 3, 4] },
    power: 12,
    scaling: "spi",
    kind: "heal",
    fx: "heal",
  },
  saltmaul: {
    id: "saltmaul",
    name: "Mazo de sal",
    launch: [1, 2],
    target: { type: "enemy", ranks: [1, 2] },
    power: 10,
    scaling: "str",
    kind: "phys",
    fx: "slash",
    effects: [{ type: "shove", amount: 1, turns: 0 }],
  },
  saltstorm: {
    id: "saltstorm",
    name: "Tormenta de cristales",
    launch: [1, 2, 3, 4],
    target: { type: "allEnemies" },
    power: 4,
    scaling: "str",
    kind: "phys",
    fx: "meteor",
    effects: [{ type: "agi", amount: -2, turns: 2 }],
  },
  petrify: {
    id: "petrify",
    name: "Petrificar",
    launch: [1, 2, 3, 4],
    target: { type: "enemy", ranks: [1, 2, 3] },
    power: 7,
    scaling: "mag",
    kind: "magic",
    fx: "frost",
    effects: [
      { type: "agi", amount: -6, turns: 2 },
      { type: "def", amount: -3, turns: 2 },
    ],
  },
  templewall: {
    id: "templewall",
    name: "Muro del templo",
    launch: [1, 2, 3, 4],
    target: { type: "self" },
    power: 0,
    kind: "buff",
    fx: "guard",
    effects: [{ type: "def", amount: 8, turns: 2 }],
  },
  columncrush: {
    id: "columncrush",
    name: "Aplastar columnas",
    launch: [1],
    target: { type: "enemy", ranks: [1, 2] },
    power: 12,
    scaling: "str",
    kind: "phys",
    fx: "charge",
  },
  thornburst: {
    id: "thornburst",
    name: "Estallido de espinas",
    launch: [1, 2, 3, 4],
    target: { type: "allEnemies" },
    power: 4,
    scaling: "str",
    kind: "phys",
    fx: "poison",
    effects: [{ type: "dot", amount: 2, turns: 2 }],
  },
  rootgrasp: {
    id: "rootgrasp",
    name: "Raíces hambrientas",
    launch: [1, 2, 3],
    target: { type: "enemy", ranks: [1, 2, 3] },
    power: 7,
    scaling: "str",
    kind: "phys",
    fx: "snare",
    effects: [{ type: "agi", amount: -4, turns: 2 }],
  },
  bloomheal: {
    id: "bloomheal",
    name: "Floración oscura",
    launch: [1, 2, 3, 4],
    target: { type: "self" },
    power: 14,
    scaling: "spi",
    kind: "heal",
    fx: "heal",
  },
  nova: {
    id: "nova",
    name: "Nova de eclipse",
    launch: [1, 2, 3, 4],
    target: { type: "allEnemies" },
    power: 5,
    scaling: "mag",
    kind: "magic",
    fx: "meteor",
  },
  lanternbeam: {
    id: "lanternbeam",
    name: "Haz del faro",
    launch: [1, 2, 3, 4],
    target: { type: "enemy", ranks: [1, 2, 3, 4] },
    power: 9,
    scaling: "mag",
    kind: "magic",
    fx: "smite",
    effects: [{ type: "marked", amount: 4, turns: 2 }],
  },
  nightfall: {
    id: "nightfall",
    name: "Caída de noche",
    launch: [1, 2, 3, 4],
    target: { type: "allEnemies" },
    power: 4,
    scaling: "mag",
    kind: "magic",
    fx: "curse",
    effects: [{ type: "atk", amount: -3, turns: 2 }],
  },
};

export const ENEMIES = {
  saltbandit: {
    id: "saltbandit",
    name: "Bandido de sal",
    colors: ["#a67c52", "#e8d5b5", "#5c3d24"],
    stats: { str: 5, mag: 2, vit: 5, agi: 5, spi: 2 },
    hp: 22,
    skills: ["saltcut", "blinddust"],
    xp: 22,
    gold: [4, 10],
  },
  glasscorpion: {
    id: "glasscorpion",
    name: "Escorpión de vidrio",
    colors: ["#4a7c6f", "#c8f0e0", "#1d3b34"],
    stats: { str: 4, mag: 3, vit: 4, agi: 6, spi: 2 },
    hp: 18,
    skills: ["sting", "glassspit", "carapace"],
    xp: 20,
    gold: [3, 8],
  },
  duneshade: {
    id: "duneshade",
    name: "Sombra de duna",
    colors: ["#3a3558", "#9b93c9", "#1a1730"],
    stats: { str: 3, mag: 7, vit: 3, agi: 6, spi: 5 },
    hp: 16,
    skills: ["voidtouch", "curse", "disperse"],
    xp: 24,
    gold: [5, 11],
  },
  adobe: {
    id: "adobe",
    name: "Gólem de adobe",
    colors: ["#b85c38", "#f2c6a0", "#6a2e18"],
    stats: { str: 5, mag: 1, vit: 9, agi: 2, spi: 2 },
    hp: 38,
    skills: ["slam", "adobedust", "harden"],
    xp: 28,
    gold: [6, 12],
  },
  coralser: {
    id: "coralser",
    name: "Serpiente de coral",
    colors: ["#c23b5a", "#ffb3c6", "#6b1c30"],
    stats: { str: 7, mag: 4, vit: 5, agi: 7, spi: 3 },
    hp: 24,
    skills: ["coralbite", "tangle", "swarm"],
    xp: 26,
    gold: [5, 12],
  },
  cultist: {
    id: "cultist",
    name: "Cultista del eclipse",
    colors: ["#5a3d7a", "#d4b8ff", "#2a1840"],
    stats: { str: 3, mag: 8, vit: 4, agi: 4, spi: 7 },
    hp: 20,
    skills: ["eclipsray", "curse", "veilhowl", "mend"],
    xp: 27,
    gold: [6, 14],
  },
  thornmatron: {
    id: "thornmatron",
    name: "Matriarca de espinas",
    colors: ["#2f6b3a", "#d4e09b", "#14331c"],
    stats: { str: 8, mag: 6, vit: 8, agi: 5, spi: 6 },
    hp: 72,
    skills: ["thornburst", "rootgrasp", "swarm", "bloomheal"],
    xp: 70,
    gold: [22, 36],
    boss: true,
  },
  saltguardian: {
    id: "saltguardian",
    name: "Guardián de sal",
    colors: ["#d4a84b", "#fff0c2", "#6b4a12"],
    stats: { str: 9, mag: 4, vit: 10, agi: 3, spi: 4 },
    hp: 64,
    skills: ["saltmaul", "saltstorm", "petrify", "templewall", "columncrush"],
    xp: 64,
    gold: [18, 30],
    boss: true,
  },
  lastlighthouse: {
    id: "lastlighthouse",
    name: "El Último Faro",
    colors: ["#1a2744", "#7ec8e3", "#0b1224"],
    stats: { str: 7, mag: 11, vit: 9, agi: 6, spi: 10 },
    hp: 96,
    skills: ["nova", "lanternbeam", "nightfall", "mend"],
    xp: 95,
    gold: [36, 55],
    boss: true,
  },
};

export const DUNGEONS = [
  {
    id: "temple",
    name: "Templo de la Arena Roja",
    tag: "Primer umbral",
    blurb: "Columnas rotas y un calor que no debería existir bajo tierra. El Guardián aún cree que el sol no se ha ido.",
    rooms: 4,
    danger: 1,
    unlock: null,
    enemies: ["saltbandit", "glasscorpion", "adobe"],
    boss: "saltguardian",
    palette: "sand",
  },
  {
    id: "gardens",
    name: "Jardines de Coral Seco",
    tag: "Segundo umbral",
    blurb: "Un oasis fosilizado. Las raíces recuerdan el agua y muerden a quien pisa sus lechos.",
    rooms: 5,
    danger: 2,
    unlock: "temple",
    enemies: ["coralser", "duneshade", "glasscorpion", "cultist"],
    boss: "thornmatron",
    palette: "coral",
  },
  {
    id: "eclipse",
    name: "Núcleo del Eclipse",
    tag: "Último umbral",
    blurb: "Aquí se quebró el día. El faro interior aún arde, y no quiere compañía.",
    rooms: 6,
    danger: 3,
    unlock: "gardens",
    enemies: ["cultist", "duneshade", "adobe", "coralser"],
    boss: "lastlighthouse",
    palette: "night",
  },
];

export const NAMES = {
  first: [
    "Zahra", "Idris", "Layla", "Cassian", "Noor", "Tariq", "Elara", "Rami",
    "Yasmin", "Sable", "Nuria", "Omar", "Samira", "Kael", "Amina", "Leandro",
    "Farah", "Selim", "Vega", "Hadir", "Sol", "Iman", "Rocco", "Qamar",
    "Neris", "Azul", "Hasan", "Mira", "Jabal", "Sera",
  ],
  last: [
    "del Velo", "Al-Nasr", "de las Dunas", "Coral", "Solano", "Qadim",
    "de Aljama", "Brisa", "de Sal", "Ember", "del Faro", "Zahir",
    "de la Teja", "Lumen", "del Adobe",
  ],
};

export const ITEM_BASES = {
  weapon: [
    { name: "Cimitarra", classes: ["warrior", "rogue"], stats: { str: 3 }, value: 18 },
    { name: "Lanza de duna", classes: ["warrior", "ranger"], stats: { str: 2, agi: 1 }, value: 18 },
    { name: "Bastón de vidrio", classes: ["mage", "cleric", "bard", "weaver"], stats: { mag: 3 }, value: 18 },
    { name: "Cetro de ámbar", classes: ["cleric", "mage", "alchemist"], stats: { spi: 2, mag: 1 }, value: 20 },
    { name: "Dagas gemelas", classes: ["rogue", "dancer"], stats: { agi: 3 }, value: 16 },
    { name: "Arco de cristal", classes: ["ranger"], stats: { agi: 2, str: 1 }, value: 18 },
    { name: "Laúd de cobre", classes: ["bard"], stats: { spi: 2, mag: 1 }, value: 17 },
    { name: "Maza de sol", classes: ["warrior", "cleric"], stats: { str: 2, spi: 1 }, value: 19 },
    { name: "Alambique de cobre", classes: ["alchemist"], stats: { mag: 2, spi: 1 }, value: 18 },
    { name: "Husos de coral", classes: ["weaver"], stats: { mag: 2, agi: 1 }, value: 17 },
    { name: "Abanico de latón", classes: ["dancer"], stats: { agi: 2, str: 1 }, value: 17 },
  ],
  armor: [
    { name: "Coraza de adobe", classes: ["warrior", "cleric"], stats: { vit: 3, def: 3 }, value: 20 },
    { name: "Manto de velo", classes: ["mage", "bard", "weaver"], stats: { mag: 2, spi: 1 }, value: 18 },
    { name: "Jubón de juncos", classes: ["rogue", "ranger", "dancer"], stats: { agi: 2, vit: 1 }, value: 17 },
    { name: "Delantal de crisol", classes: ["alchemist"], stats: { mag: 1, vit: 2 }, value: 17 },
    { name: "Túnica de teja", classes: null, stats: { vit: 2, def: 1 }, value: 14 },
    { name: "Cota de coral", classes: ["warrior", "ranger", "cleric"], stats: { def: 4, vit: 1 }, value: 22 },
  ],
  accessory: [
    { name: "Amuleto de sal", classes: null, stats: { spi: 2 }, value: 14 },
    { name: "Anillo del faro", classes: null, stats: { mag: 2 }, value: 14 },
    { name: "Pendiente de duna", classes: null, stats: { agi: 2 }, value: 14 },
    { name: "Sello de aljama", classes: null, stats: { str: 1, vit: 1 }, value: 16 },
    { name: "Broche de aurora", classes: null, stats: { spi: 1, mag: 1 }, value: 16 },
  ],
};

export const ITEM_PREFIXES = [
  { name: "del Alba", stats: { spi: 1 } },
  { name: "de Coral", stats: { vit: 1 } },
  { name: "Solar", stats: { str: 1 } },
  { name: "de Sal", stats: { def: 1 } },
  { name: "del Velo", stats: { mag: 1 } },
  { name: "Qadim", stats: { agi: 1 } },
];

export const EFFECT_LABELS = {
  def: "Defensa",
  atk: "Ataque",
  agi: "Agilidad",
  dodge: "Evasión",
  shield: "Escudo",
  taunt: "Provoca",
  marked: "Marcado",
  dot: "Veneno",
  crust: "Costra",
  wound: "Herida",
};

export const HAZARDS = {
  glare: {
    id: "glare",
    name: "Resplandor de sal",
    desc: "Las curas restauran un 45% menos. El velo quema la sutura.",
  },
  quake: {
    id: "quake",
    name: "Temblor de duna",
    desc: "Cada ronda, un caminante al azar cambia de puesto.",
  },
  thorns: {
    id: "thorns",
    name: "Cristales vivos",
    desc: "Golpear al frente enemigo (puesto 1) devuelve 4 de daño.",
  },
  eclipse: {
    id: "eclipse",
    name: "Sombra de eclipse",
    desc: "La magia inflige un 25% más. Los golpes físicos, un 20% menos.",
  },
  heat: {
    id: "heat",
    name: "Horno residual",
    desc: "Al cierre de cada ronda, toda la sala pierde 3 de vitalidad.",
  },
  hush: {
    id: "hush",
    name: "Silencio de teja",
    desc: "Los refuerzos (buffs) duran un turno menos.",
  },
};

export const STAT_LABELS = {
  str: "Fuerza",
  mag: "Canal",
  vit: "Temple",
  agi: "Agilidad",
  spi: "Espíritu",
  def: "Defensa",
};
